resolver: lts-7.11
packages:
  - '.'
extra-deps:
flags:
extra-package-dbs: []

# will use system-wide installed GHC (e.g. HaskellPlatform)
# system-ghc: true

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64
#
# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
